language: ruby
script: 'bundle exec rake ci'
rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --1.9"
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"
